package com.lge.kdadmin;
import android.app.*;import android.os.*;import android.graphics.Color;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{
 android.content.SharedPreferences sp;EditText code,pkg;TextView status;Spinner list;ArrayList<Device>ds=new ArrayList<>();
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("relay",0);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(20,24,20,20);TextView t=new TextView(this);t.setText("KDAdmin");t.setTextSize(30);t.setTextColor(Color.BLACK);r.addView(t);status=new TextView(this);status.setText("Free internet relay — no server or Wi-Fi required");r.addView(status);code=f("Kodroid pairing code","");r.addView(code);Button p=btn("Pair device");p.setOnClickListener(v->new Thread(()->pair()).start());r.addView(p);list=new Spinner(this);r.addView(list);pkg=f("Package name","com.google.android.apps.maps");r.addView(pkg);for(String[]x:new String[][]{{"Lock","LOCK"},{"Hide","HIDE"},{"Unhide","UNHIDE"},{"Suspend","SUSPEND"},{"Unsuspend","UNSUSPEND"},{"Block uninstall","BLOCK_UNINSTALL"},{"Unblock uninstall","UNBLOCK_UNINSTALL"},{"Clear app data","CLEAR_APP_STORAGE"}}){Button q=btn(x[0]);q.setOnClickListener(v->send(x[1]));r.addView(q);}setContentView(r);load();}
 EditText f(String h,String v){EditText e=new EditText(this);e.setHint(h);e.setText(v);e.setSingleLine(true);return e;}Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void pair(){try{String want=code.getText().toString().trim();String stream=Relay.poll(Relay.PAIR,sp.getString("lastPair",""));for(String line:stream.split("\\n")){String msg=Relay.json(line,"message"),id=Relay.json(line,"id");if(id!=null)sp.edit().putString("lastPair",id).apply();if(msg==null||!msg.startsWith("HELLO|"))continue;String[]p=msg.split("\\|",6);if(p.length<6||!want.equals(p[1]))continue;java.security.PublicKey pub=Relay.publicKey(p[2]);byte[]key=new byte[32];new java.security.SecureRandom().nextBytes(key);Relay.post(p[3],"PAIR:"+Relay.encryptKey(key,pub));String topic="kd-cmd-"+topic(key);String name=p[4]+" ("+p[5]+")";ds.add(new Device(name,topic,key));save();runOnUiThread(()->{status.setText("Paired: "+name);refresh();});return;}runOnUiThread(()->status.setText("Device not found yet — try again"));}catch(Exception e){runOnUiThread(()->status.setText("Pairing error"));}}
 String topic(byte[]k){return Relay.b64(k).replace("=","").replace("/","_").replace("+","-");}
 void send(String a){if(ds.size()==0){status.setText("Pair a device first");return;}int n=list.getSelectedItemPosition();if(n<0||n>=ds.size())return;Device d=ds.get(n);try{String p=pkg.getText().toString().trim();String j="{\"action\":\""+a+"\",\"packageName\":\""+p.replace("\"","\\\"")+"\"}";Relay.post(d.topic,Relay.enc(j,d.key),"Title","KDAdmin command");status.setText("Sent "+a+" to "+d.name);}catch(Exception e){status.setText("Command failed");}}
 void refresh(){String[]a=new String[ds.size()];for(int i=0;i<ds.size();i++)a[i]=ds.get(i).name;list.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));}
 void load(){String raw=sp.getString("devices","");if(raw.length()>0)for(String z:raw.split(";;")){String[]p=z.split("\\|",4);if(p.length>=3)try{ds.add(new Device(p[0],p[1],Relay.unb(p[2])));}catch(Exception ignored){}}refresh();}
 void save(){StringBuilder b=new StringBuilder();for(Device d:ds){if(b.length()>0)b.append(";;");b.append(d.name.replace("|"," ")).append("|").append(d.topic).append("|").append(Relay.b64(d.key));}sp.edit().putString("devices",b.toString()).apply();}
 static class Device{String name,topic;byte[]key;Device(String n,String t,byte[]k){name=n;topic=t;key=k;}}
}