package com.lge.kdadmin;
import android.app.*;import android.os.*;import android.graphics.Color;import android.widget.*;import java.io.*;import java.net.*;
public class MainActivity extends Activity{
 EditText server,email,pass,code,pkg;TextView status,devices;String token="";
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(24,24,24,24);TextView t=new TextView(this);t.setText("KDAdmin");t.setTextSize(30);t.setTextColor(Color.BLACK);r.addView(t);status=new TextView(this);status.setText("Sign in to manage devices");r.addView(status);server=f("Server address","");email=f("Email","");pass=f("Password","");code=f("Pairing code","");pkg=f("Package name","com.google.android.apps.maps");r.addView(server);r.addView(email);r.addView(pass);Button l=btn("Sign in / create account");l.setOnClickListener(v->auth());r.addView(l);r.addView(code);Button p=btn("Pair device");p.setOnClickListener(v->claim());r.addView(p);devices=new TextView(this);devices.setText("No devices loaded");r.addView(devices);r.addView(pkg);for(String[] x:new String[][]{{"Lock","LOCK"},{"Hide","HIDE"},{"Unhide","UNHIDE"},{"Suspend","SUSPEND"},{"Unsuspend","UNSUSPEND"}}){Button q=btn(x[0]);q.setOnClickListener(v->command(x[1],x[1].equals("LOCK")?null:pkg.getText().toString()));r.addView(q);}setContentView(r);}
 EditText f(String h,String v){EditText e=new EditText(this);e.setHint(h);e.setText(v);e.setSingleLine(true);return e;}Button btn(String s){Button b=new Button(this);b.setText(s);return b;}String base(){return server.getText().toString().trim().replaceAll("/+$","");}
 void auth(){new Thread(()->{try{String p="{\"email\":\""+esc(email.getText().toString())+"\",\"password\":\""+esc(pass.getText().toString())+"\"}";String x=post(base()+"/v1/auth/login",p,null);String z=find(x,"token");if(z==null){post(base()+"/v1/auth/register",p,null);x=post(base()+"/v1/auth/login",p,null);z=find(x,"token");}token=z==null?"":z;runOnUiThread(()->status.setText(token.length()>0?"Signed in":"Sign-in failed"));load();}catch(Exception e){err(e);}}).start();}
 void claim(){new Thread(()->{try{String x=post(base()+"/v1/devices/pair/claim","{\"code\":\""+esc(code.getText().toString())+"\"}",token);runOnUiThread(()->status.setText(x.contains("\"device\"")?"Device paired":"Pairing failed"));load();}catch(Exception e){err(e);}}).start();}
 void load(){try{String x=get(base()+"/v1/devices",token);runOnUiThread(()->devices.setText(x));}catch(Exception e){}}
 void command(String a,String p){new Thread(()->{try{String d=find(devices.getText().toString(),"id");if(d==null){runOnUiThread(()->status.setText("Pair a device first"));return;}String b="{\"action\":\""+a+"\",\"packageName\":"+(p==null?"\"\"":"\""+esc(p)+"\"")+"}";post(base()+"/v1/devices/"+d+"/commands",b,token);runOnUiThread(()->status.setText(a+" queued"));}catch(Exception e){err(e);}}).start();}
 String post(String u,String b,String t)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(8000);c.setReadTimeout(8000);c.setRequestProperty("Content-Type","application/json");if(t!=null)c.setRequestProperty("Authorization","Bearer "+t);c.getOutputStream().write(b.getBytes("UTF-8"));return read(c);}String get(String u,String t)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("GET");c.setConnectTimeout(8000);c.setReadTimeout(8000);c.setRequestProperty("Authorization","Bearer "+t);return read(c);}String read(HttpURLConnection c)throws Exception{int n=c.getResponseCode();InputStream in=n>=400?c.getErrorStream():c.getInputStream();if(in==null)return "";ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[2048];int x;while((x=in.read(b))!=-1)o.write(b,0,x);return o.toString("UTF-8");}String find(String j,String k){String q="\""+k+"\":\"";int i=j.indexOf(q);if(i<0)return null;i+=q.length();int e=j.indexOf("\"",i);return e<0?null:j.substring(i,e);}String esc(String s){return s.replace("\\","\\\\").replace("\"","\\\"");}void err(Exception e){runOnUiThread(()->status.setText("Error: "+e.getClass().getSimpleName()));}
}