package com.lge.kdadmin;
import android.app.*;import android.view.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.widget.*;import java.security.*;import java.util.*;
public class MainActivity extends Activity{
 android.content.SharedPreferences sp;EditText code,pkg;TextView status,detail,apps,policy;Spinner list;ArrayList<Device>ds=new ArrayList<>();int blue=Color.rgb(38,99,235),dark=Color.rgb(20,28,45);
 TextView t(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(dark);v.setPadding(0,5,0,5);return v;}
 GradientDrawable g(int c){GradientDrawable x=new GradientDrawable();x.setColor(c);x.setCornerRadius(28);return x;}
 LinearLayout sec(String s){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(22,18,22,18);l.setBackground(g(Color.WHITE));TextView h=t(s,19);h.setTypeface(null,1);l.addView(h);return l;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setTextSize(14);x.setTextColor(Color.WHITE);x.setBackground(g(blue));return x;}
 EditText e(String h){EditText x=new EditText(this);x.setHint(h);x.setSingleLine(true);x.setTextSize(16);return x;}
 View gap(){Space s=new Space(this);s.setMinimumHeight(12);return s;}
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("kdadmin",MODE_PRIVATE);ui();load();}
 void ui(){ScrollView sc=new ScrollView(this);sc.setBackgroundColor(Color.rgb(245,247,251));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(22,28,22,28);sc.addView(r);TextView h=t("KDADMIN",30);h.setTypeface(null,1);r.addView(h);r.addView(t("Remote device control center",15));
  LinearLayout d=sec("Devices");r.addView(gap());r.addView(d);code=e("Kodroid pairing code");d.addView(code);Button pair=b("Pair device");pair.setOnClickListener(v->new Thread(this::pair).start());d.addView(pair);list=new Spinner(this);d.addView(list);detail=t("No device paired.",14);d.addView(detail);
  LinearLayout m=sec("Management");r.addView(gap());r.addView(m);pkg=e("Package name");pkg.setText("com.google.android.apps.maps");m.addView(pkg);String[][]a={{"Lock device","LOCK"},{"Hide app","HIDE"},{"Unhide app","UNHIDE"},{"Suspend app","SUSPEND"},{"Unsuspend app","UNSUSPEND"},{"Block uninstall","BLOCK_UNINSTALL"},{"Allow uninstall","UNBLOCK_UNINSTALL"},{"Clear app data","CLEAR_APP_STORAGE"},{"Disable camera","SET_CAMERA_DISABLED"},{"Enable camera","SET_CAMERA_ENABLED"},{"Disable screenshots","SET_SCREEN_CAPTURE_DISABLED"},{"Enable screenshots","SET_SCREEN_CAPTURE_ENABLED"}};for(String[]x:a){Button q=b(x[0]);q.setOnClickListener(v->send(x[1]));m.addView(q);}
  LinearLayout i=sec("App inventory");r.addView(gap());r.addView(i);apps=t("Requesting inventory will show system and user packages returned by Kodroid.",14);i.addView(apps);Button li=b("Refresh app inventory");li.setOnClickListener(v->send("LIST_APPS"));i.addView(li);
  LinearLayout p=sec("Policy workspace");r.addView(gap());r.addView(p);policy=t("Save a named policy locally, review it, then apply it to the selected device.",14);p.addView(policy);Button save=b("Save current settings");save.setOnClickListener(v->savePolicy());p.addView(save);Button review=b("Review saved policy");review.setOnClickListener(v->review());p.addView(review);
  status=t("Secure relay ready.",14);r.addView(gap());r.addView(status);r.addView(t("Encrypted per-device relay • OwnDroid-compatible policy controls • designed for D-pad navigation",13));setContentView(sc);}
 void pair(){try{String want=code.getText().toString().trim();String z=Relay.poll(Relay.PAIR,sp.getString("lastPair",""));for(String x:z.split("\\n")){String m=Relay.json(x,"message"),id=Relay.json(x,"id");if(id!=null)sp.edit().putString("lastPair",id).apply();if(m==null||!m.startsWith("HELLO|"))continue;String[]p=m.split("\\|",6);if(p.length<6||!want.equals(p[1]))continue;byte[]k=new byte[32];new SecureRandom().nextBytes(k);Relay.post(p[3],"PAIR:"+Relay.encryptKey(k,Relay.publicKey(p[2])));ds.add(new Device(p[4]+" ("+p[5]+")","kd-cmd-"+topic(k),k));save();runOnUiThread(()->{status.setText("✓ Device securely paired");refresh();});return;}runOnUiThread(()->status.setText("Device not found — leave Kodroid open and retry"));}catch(Exception e){runOnUiThread(()->status.setText("Pairing error — check internet"));}}
 String topic(byte[]k){return Relay.b64(k).replace("=","").replace("/","_").replace("+","-");}
 void send(String a){if(ds.isEmpty()){status.setText("Pair a device first");return;}Device d=ds.get(list.getSelectedItemPosition());try{String p=pkg.getText().toString().trim();Relay.post(d.topic,Relay.enc("{\"action\":\""+a+"\",\"packageName\":\""+p.replace("\"","\\\"")+"\"}",d.key));status.setText("Sent "+a+" • waiting for acknowledgement");}catch(Exception e){status.setText("Command failed");}}
 void refresh(){String[]a=new String[ds.size()];for(int i=0;i<ds.size();i++)a[i]=ds.get(i).name;list.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));if(!ds.isEmpty())detail.setText("✓ "+ds.get(0).name+"\nEncrypted relay connected\nOwnDroid-compatible policy engine");}
 void load(){String z=sp.getString("devices","");if(!z.isEmpty())for(String x:z.split(";;")){String[]p=x.split("\\|",4);if(p.length>=3)try{ds.add(new Device(p[0],p[1],Relay.unb(p[2])));}catch(Exception e){}}refresh();new Thread(this::acks).start();}
 void save(){StringBuilder s=new StringBuilder();for(Device d:ds){if(s.length()>0)s.append(";;");s.append(d.name.replace("|"," ")).append("|").append(d.topic).append("|").append(Relay.b64(d.key));}sp.edit().putString("devices",s.toString()).apply();}
 void acks(){while(true){try{for(Device d:ds){String k="ack_"+d.topic,last=sp.getString(k,"");String z=Relay.poll("kd-ack-"+topic(d.key),last);for(String x:z.split("\\n")){String m=Relay.json(x,"message"),id=Relay.json(x,"id");if(id!=null)sp.edit().putString(k,id).apply();if(m!=null&&!m.isEmpty()){String j=Relay.dec(m,d.key),a=Relay.json(j,"action"),ok=Relay.json(j,"ok"),ap=Relay.json(j,"apps");runOnUiThread(()->{status.setText(("true".equals(ok)?"✓ ":"⚠ ")+a+" acknowledged");if(ap!=null)apps.setText(ap.length()>5000?ap.substring(0,5000)+"…":ap);});}}}Thread.sleep(4000);}catch(Exception e){try{Thread.sleep(5000);}catch(Exception x){}}}}
 void savePolicy(){String p="Package="+pkg.getText().toString()+"\nSelected device="+(ds.isEmpty()?"none":ds.get(0).name);sp.edit().putString("policy",p).apply();policy.setText("Saved policy:\n"+p);}
 void review(){String p=sp.getString("policy","");new AlertDialog.Builder(this).setTitle("Review policy").setMessage(p.isEmpty()?"No saved policy.":p+"\n\nReview before sending changes.").setNegativeButton("Cancel",null).setPositiveButton("Done",null).show();}
 static class Device{String name,topic;byte[]key;Device(String n,String t,byte[]k){name=n;topic=t;key=k;}}
}