package com.lge.kdadmin;
import android.util.Base64;import java.io.*;import java.net.*;import java.security.*;import javax.crypto.*;import javax.crypto.spec.*;import java.nio.charset.StandardCharsets;
public final class Relay{
 public static final String HOST="https://ntfy.sh",PAIR="kodroid-pair-v1";
 public static String b64(byte[]b){return Base64.encodeToString(b,Base64.NO_WRAP|Base64.URL_SAFE);}public static byte[]unb(String s){return Base64.decode(s,Base64.NO_WRAP|Base64.URL_SAFE);}
 public static PublicKey publicKey(String s)throws Exception{return KeyFactory.getInstance("RSA").generatePublic(new java.security.spec.X509EncodedKeySpec(unb(s)));}
 public static String encryptKey(byte[]k,PublicKey p)throws Exception{Cipher c=Cipher.getInstance("RSA/ECB/PKCS1Padding");c.init(1,p);return b64(c.doFinal(k));}
 public static String enc(String s,byte[]k)throws Exception{byte[]iv=new byte[12];new SecureRandom().nextBytes(iv);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(1,new SecretKeySpec(k,"AES"),new GCMParameterSpec(128,iv));return b64(iv)+":"+b64(c.doFinal(s.getBytes(StandardCharsets.UTF_8)));}
 public static String dec(String s,byte[]k)throws Exception{String[]p=s.split(":",2);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(2,new SecretKeySpec(k,"AES"),new GCMParameterSpec(128,unb(p[0])));return new String(c.doFinal(unb(p[1])),StandardCharsets.UTF_8);}
 public static String post(String t,String body,String...h)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(HOST+"/"+t).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(10000);c.setReadTimeout(10000);for(int i=0;i+1<h.length;i+=2)c.setRequestProperty(h[i],h[i+1]);c.getOutputStream().write(body.getBytes("UTF-8"));return read(c);}
 public static String poll(String t,String since)throws Exception{String u=HOST+"/"+t+"/json?poll=1"+(since.length()>0?"&since="+URLEncoder.encode(since,"UTF-8"):"");HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);return read(c);}
 static String read(HttpURLConnection c)throws Exception{InputStream in=c.getResponseCode()>=400?c.getErrorStream():c.getInputStream();if(in==null)return "";ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[4096];int x;while((x=in.read(b))!=-1)o.write(b,0,x);return o.toString("UTF-8");}
 public static String json(String j,String k){String q="\""+k+"\":";int i=j.indexOf(q);if(i<0)return null;i+=q.length();while(i<j.length()&&Character.isWhitespace(j.charAt(i)))i++;if(i<j.length()&&j.charAt(i)=='\"'){i++;int e=j.indexOf("\"",i);return e<0?null:j.substring(i,e);}int e=i;while(e<j.length()&&",}\n".indexOf(j.charAt(e))<0)e++;return j.substring(i,e).trim();}
}